Renamed cadinstall directory to cadinstaller
Need to have a different name for this directory than the package
(cadinstall.py), otherwise there's a naming conflict and youll get this
kind of message on invocation:
ModuleNotFoundError: No module named 'cadinstall.log'; 'cadinstall' is
not a package